Ecommerce_ projet/Models/Vendeur.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce__projet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendeur
    {
        public string identifiant { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
    }
}

Ecommerce_ projet/Controllers/ProduitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Ecommerce__projet.Models;
namespace Ecommerce__projet.Controllers
{
    public class ProduitController : Controller
    {

        BdecommerceEntities db= new BdecommerceEntities();
        // GET: Produit
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult modifier(Produit produit, HttpPostedFileBase photo)
        {
            string fil = null;
            if (photo != null)
            {
                fil = System.IO.Path.GetFileName(photo.FileName);
                string path = System.IO.Path.Combine(Server.MapPath("~/PhotoProduit/"), fil);
                photo.SaveAs(path);
            }
            Produit pr = new Produit();

            pr.idproduit = produit.idproduit;
            pr.nom = produit.nom;
            pr.prix = produit.prix;
            pr.quantite = produit.quantite;
            pr.image = fil;
            db.Produit.Add(pr);
            return View("ajouter");

        }
        public ActionResult ajouter(Produit produit, HttpPostedFileBase photo)
        {

            string fil = null;
            if (photo != null)
            {
                fil = System.IO.Path.GetFileName(photo.FileName);
                string path = System.IO.Path.Combine(Server.MapPath("~/PhotoProduit/"), fil);
                photo.SaveAs(path);
            }
            Produit pr = new Produit();

            pr.idproduit = produit.idproduit;
            pr.nom = produit.nom;
            pr.prix = produit.prix;
            pr.quantite = produit.quantite;
            pr.image = fil;
            db.Produit.Add(pr);
            return View("ajouter");

        }
        [HttpPost]
        public ActionResult CreatePro(Produit produit,HttpPostedFileBase photo)
        {
            string fil=null;
            if(photo!=null)
            {
                 fil = System.IO.Path.GetFileName(photo.FileName);
                string path = System.IO.Path.Combine(Server.MapPath("~/PhotoProduit/"), fil);
                photo.SaveAs(path);
            }
            Produit pr = new Produit();

            pr.idproduit = produit.idproduit;
            pr.nom = produit.nom;
            pr.prix = produit.prix;
            pr.quantite = produit.quantite;
            pr.image = fil;
            db.Produit.Add(pr);
            db.SaveChanges();
            return View("ajouter");

        }
    }
}

Ecommerce_ projet/Controllers/VendeurController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ecommerce__projet.Models;
namespace Ecommerce__projet.Controllers
{
    public class VendeurController : Controller
    {
        BdecommerceEntities bd=new BdecommerceEntities();
        // GET: Vendeur
        public ActionResult Vendeur()
        {
            var getvendeur = bd.Vendeur.ToList();
            SelectList list = new SelectList(getvendeur, "identifiant", "identifiant");
            ViewBag.listvendeur = list;
            return View();
        }
        public ActionResult Vend()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ajoutVendeur(Vendeur vendeur)
        {
            Vendeur v=new Vendeur();
            v.identifiant = vendeur.identifiant;
            v.nom = vendeur.nom;
            v.prenom = vendeur.prenom;
            bd.Vendeur.Add(v);
            bd.SaveChanges();
            return View("Vend");
        }
      public ActionResult listeproduit()
        {
            var res = bd.Produit.ToList();
        
            return View(res);
        }
       
        public ActionResult PageVendeur()
        {

            return View();
        }
        public ActionResult Delete(int id)
        {
            var res = bd.Produit.Where(x => x.idproduit == id).First();
            bd.Produit.Remove(res);
            bd.SaveChanges();
            var list = bd.Produit.ToList();
            return View("listeproduit", list);
        }
        public ActionResult affichercommande()
        {
            var resul = bd.Commande.ToList();

            return View(resul);
        }
        public ActionResult ChoixDuVendeur()
        {

            var getclient = bd.Vendeur.ToList();
            SelectList list = new SelectList(getclient, "identifiant", "identifiant");
            ViewBag.listvendeur = list;
            return View();
        }

        [HttpPost]
        public ActionResult ChoixDuVendeur(Vendeur vendeur)
        {
            var user = bd.Vendeur.SingleOrDefault(x => x.identifiant == vendeur.identifiant);

            if (user != null)
            {
                ViewBag.message = "vous etes conecter";
                ViewBag.triedOnce = "yes";
                Session["identifiant"] = vendeur.identifiant;
                return RedirectToAction("PageVendeur", "Vendeur", new { identifiant = vendeur.identifiant });
            }
            else
            {
                ViewBag.triedOnce = "yes";
                var getvendeur = bd.Vendeur.ToList();
                SelectList list = new SelectList(getvendeur, "identifiant", "identifiant");
                ViewBag.listvendeur = list;

                return View();
            }
        }
        public ActionResult InscrireVendeur()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AjouterVendeur(Vendeur v)
        {
            Vendeur cli = new Vendeur();
            cli.identifiant = v.identifiant;
            cli.nom = v.nom;
            cli.prenom = v.prenom;
            bd.Vendeur.Add(cli);
            bd.SaveChanges();
            return View("InscrireVendeur");
        }
    }
}

Ecommerce_ projet/Views/Vendeur/ChoixDuVendeur.cshtml
@model Ecommerce__projet.Models.Vendeur

<!DOCTYPE html>

<html lang="zxx">
<head>
    <!-- Meta Tag -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name='copyright' content=''>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Title Tag  -->
    <title>Eshop - eCommerce HTML5 Template.</title>
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="images/favicon.png">
    <!-- Web Font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

    <!-- StyleSheet -->
    <!-- Bootstrap -->
    <link href="~/DesignClient/css/bootstrap.css" rel="stylesheet" />
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/DesignClient/css/magnific-popup.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/DesignClient/css/font-awesome.css">
    <!-- Fancybox -->
    <link rel="stylesheet" href="~/DesignClient/css/jquery.fancybox.min.css">
    <!-- Themify Icons -->
    <link rel="stylesheet" href="~/DesignClient/css/themify-icons.css">
    <!-- Nice Select CSS -->
    <link rel="stylesheet" href="~/DesignClient/css/niceselect.css">
    <!-- Animate CSS -->
    <link rel="stylesheet" href="~/DesignClient/css/animate.css">
    <!-- Flex Slider CSS -->
    <link rel="stylesheet" href="~/DesignClient/css/flex-slider.min.css">
    <!-- Owl Carousel -->
    <link rel="stylesheet" href="~/DesignClient/css/owl-carousel.css">
    <!-- Slicknav -->
    <link rel="stylesheet" href="~/DesignClient/css/slicknav.min.css">

    <!-- Eshop StyleSheet -->
    <link rel="stylesheet" href="~/DesignClient/css/reset.css">
    <link rel="stylesheet" href="~/DesignClient/style.css">
    <link rel="stylesheet" href="~/DesignClient/css/responsive.css">



</head>
<body class="js">

    <section class="shop checkout section" style="background-color:darkorange">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-12">
                    <div class="checkout-form">
                        <h2>BIENVENUE</h2>
                        <p>choisir un identifiant ou creer un nouveau </p>
                        @using (Html.BeginForm("listeproduit", "Vendeur"))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <h4>Vendeur</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.DropDownList("listvendeur", ViewBag.listvendeur as SelectList, "Choisissez un identifiant")

                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Valider" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }


                        <div>

                            @Html.ActionLink("Ajouter un nouveau client", "InscrireVendeur")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Form -->
</body>
</html>

Ecommerce_ projet/Views/Vendeur/InscrireVendeur.cshtml
@model Ecommerce__projet.Models.Vendeur

<!DOCTYPE html>

<html lang="zxx">
<head>
    <!-- Meta Tag -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name='copyright' content=''>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Title Tag  -->
    <title>Eshop - eCommerce HTML5 Template.</title>
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="images/favicon.png">
    <!-- Web Font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

    <!-- StyleSheet -->
    <!-- Bootstrap -->
    <link href="~/DesignClient/css/bootstrap.css" rel="stylesheet" />
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/DesignClient/css/magnific-popup.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/DesignClient/css/font-awesome.css">
    <!-- Fancybox -->
    <link rel="stylesheet" href="~/DesignClient/css/jquery.fancybox.min.css">
    <!-- Themify Icons -->
    <link rel="stylesheet" href="~/DesignClient/css/themify-icons.css">
    <!-- Nice Select CSS -->
    <link rel="stylesheet" href="~/DesignClient/css/niceselect.css">
    <!-- Animate CSS -->
    <link rel="stylesheet" href="~/DesignClient/css/animate.css">
    <!-- Flex Slider CSS -->
    <link rel="stylesheet" href="~/DesignClient/css/flex-slider.min.css">
    <!-- Owl Carousel -->
    <link rel="stylesheet" href="~/DesignClient/css/owl-carousel.css">
    <!-- Slicknav -->
    <link rel="stylesheet" href="~/DesignClient/css/slicknav.min.css">

    <!-- Eshop StyleSheet -->
    <link rel="stylesheet" href="~/DesignClient/css/reset.css">
    <link rel="stylesheet" href="~/DesignClient/style.css">
    <link rel="stylesheet" href="~/DesignClient/css/responsive.css">



</head>
<body class="js">

    <section class="shop checkout section" style="background-color:darkorange">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-12">
                    <div class="checkout-form">
                        <h2>BIENVENUE</h2>
                        <p>Creation d'un nouveau client</p>
                        @using (Html.BeginForm("AjouterVendeur", "Vendeur"))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <h4>Vendeur</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.identifiant, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.identifiant, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.identifiant, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.prenom, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.prenom, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.prenom, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }

                        <div>
                            @Html.ActionLink("Retourner", "ChoixDuVendeur")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Form -->
</body>
</html>

Ecommerce_ projet/Views/Vendeur/PageVendeur.cshtml
@{
    ViewBag.Title = "PageVendeur";
    Layout = "~/Views/Shared/_LayoutVendre.cshtml";
}

<h2>PageVendeur</h2>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- Bootstrap core CSS-->
    <link href="~/Content/sbootstrap.css" rel="stylesheet" />
    <link href="~/Content/MyMainLayOut.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body id="page-top">
    
    
</body>

</html>

Ecommerce_ projet/Views/Vendeur/Vend.cshtml
@model Ecommerce__projet.Models.Vendeur

@{
    ViewBag.Title = "Vend";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("ajoutVendeur", "Vendeur",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vendeur</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.identifiant, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.identifiant, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.identifiant, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retourner", "Vendeur", "Vendeur")
</div>

Ecommerce_ projet/Views/Vendeur/Vendeur.cshtml
@model Ecommerce__projet.Models.Vendeur

@{
    ViewBag.Title = "Vendeur";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Vendeur</h2>

<div style="float:center">
    @Html.DropDownList("vendeurlist", ViewBag.listvendeur as SelectList, "Choisissez un identifiant")

    <li>@Html.ActionLink("Creer un Vendeur", "Vend", "Vendeur")</li>




</div>

Ecommerce_ projet/Views/Vendeur/affichercommande.cshtml
@model IEnumerable<Ecommerce__projet.Models.Commande>
@{ ViewBag.Title = "affichercommande";
    Layout = "~/Views/Shared/_LayoutVendre.cshtml";

}


</br>
</br></br></br></br>
<h2>Les Commandes</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.idcommande)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.identifiantClient)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.quantite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prix_total)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idcommande)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.identifiantClient)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prix_total)
            </td>

        </tr>
    }

</table>

Ecommerce_ projet/Views/Vendeur/listeproduit.cshtml
@model IEnumerable<Ecommerce__projet.Models.Produit>

@{ ViewBag.Title = "ajoutprod";
                Layout = "~/Views/Shared/_LayoutVendre.cshtml"; }

<h2>ajoutprod</h2>


<div>
    <a href="@Url.Action("ajouter","Produit")" class="btn btn-primary"> Ajouter un produit</a>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.idproduit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.quantite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.image)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.idproduit)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.nom)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.prix)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.quantite)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.image)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
        <a href="@Url.Action("Delete", new { id=item.idproduit  })" class="btn btn-danger"> Suppprimer</a>
    </td>
</tr>}

</table>